### ISSUE TITLE
Naming convention is absolutely wrong

### ISSUE THREAD

**Issue by SuperJMN** [Vantiv/litle-sdk-for-dotNet#32]
Please, review the naming convention of the code. The API for .NET seems to be ported from other language without adapting the naming, so this NET version looks really awkward to use. For example, class names should NEVER be in lowercase, but in camel case.

If you need some guidelines, please contact me.

**Comment by brianarnold789** [comment]
We are working through this as time permits, 11.0 branch is the only one that will be updated.
