### ISSUE TITLE
Our dependencies should be included in the release zip file

### ISSUE THREAD

**Issue by GregDake** [Vantiv/litle-sdk-for-dotNet#33]
If not, when a merchant tries to use sftp, they will get an error like:

Could not load file or assembly 'Tamir.SharpSSH, Version=1.1.1.13, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

This could be fixed with changes to kit.bat

**Comment by brianarnold789** [comment]
Bundled dependencies into zip and created [NuGet](https://www.nuget.org/packages/Vantiv.LitleSdkForNet/) repo
